title: "Piotr Wosiak - Offensive Security Expert"
description: "Offensive Security Expert and Full Stack Developer specializing in red teaming operations, penetration testing, and application development."
url: "https://wosienko.github.io"
baseurl: "" 

author: "Piotr Wosiak"
social:
  name: "Piotr Wosiak"
  links:
    - "https://linkedin.com/in/piotr-wosiak"
    - "https://github.com/wosienko"